name: Release Helm Chart

on:
  push:
    branches:
      - main

env:
  REGISTRY: registry-1.docker.io
  CHART_NAME: helm-microservice-chart
  VERSION: 1.0.${{ github.run_number }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Update Chart version
        run: |
          sed -i "s/^version:.*/version: ${{ env.VERSION }}/" Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${{ env.VERSION }}\"/" Chart.yaml
          cat Chart.yaml

      - name: Lint Helm Chart
        run: helm lint .

      - name: Package Helm Chart
        run: helm package .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Chart to Docker Hub OCI Registry
        run: |
          helm push ${{ env.CHART_NAME }}-${{ env.VERSION }}.tgz oci://registry-1.docker.io/edisonpaul4
